"""evidence-first duty data model

Revision ID: 14691feaef80
Revises: 2b3646342c9b
Create Date: 2026-08-23 01:33:36.445646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14691feaef80'
down_revision: Union[str, Sequence[str], None] = '2b3646342c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Created explicitly, once, before any table references it — see
    # the matching note in the previous migration (2b3646342c9b) for why
    # this DO-block idiom is used instead of SQLAlchemy's checkfirst.
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE duty_verification_status AS ENUM (
                'VERIFIED', 'NOT_VERIFIED', 'CONFLICTING', 'EXPIRED'
            );
        EXCEPTION WHEN duplicate_object THEN null;
        END $$;
        """
    )
    duty_verification_status_enum = postgresql.ENUM(
        'VERIFIED', 'NOT_VERIFIED', 'CONFLICTING', 'EXPIRED',
        name='duty_verification_status',
        create_type=False,
    )

    op.create_table('ref_duty_components',
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('verification_status', duty_verification_status_enum, nullable=False),
    sa.Column('value_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('source_authority', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("(verification_status = 'VERIFIED' AND value_pct IS NOT NULL) OR (verification_status != 'VERIFIED' AND value_pct IS NULL)", name='ck_rdc_value_matches_status'),
    sa.CheckConstraint("component IN ('BCD','AIDC','SWS','IGST')", name='ck_rdc_component'),
    sa.PrimaryKeyConstraint('hs8', 'component', 'effective_from')
    )
    op.create_table('ref_duty_component_conflicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('candidate_value_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source_authority', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hs8', 'component', 'effective_from'], ['ref_duty_components.hs8', 'ref_duty_components.component', 'ref_duty_components.effective_from'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also detected the checkpoint_* tables as "removed"
    # (LangGraph's own tables, not ours — see the matching note in the
    # previous migration for why). Stripped by hand, same as before.
    op.drop_table('ref_duty_rates')
    op.add_column('analytics_landed_cost', sa.Column('sws_inr_paise_per_kg', sa.BigInteger(), nullable=True))
    op.add_column('analytics_landed_cost', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.add_column('analytics_landed_cost', sa.Column('excluded_components', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('analytics_landed_cost', sa.Column('partial_landed_cost_inr_paise_per_kg', sa.BigInteger(), nullable=True))
    op.alter_column('analytics_landed_cost', 'bcd_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('analytics_landed_cost', 'aidc_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('analytics_landed_cost', 'igst_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('analytics_landed_cost', 'landed_cost_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('analytics_landed_cost', 'duty_rate_effective_from')
    op.drop_column('analytics_landed_cost', 'surcharge_inr_paise_per_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_landed_cost', sa.Column('surcharge_inr_paise_per_kg', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('analytics_landed_cost', sa.Column('duty_rate_effective_from', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('analytics_landed_cost', 'landed_cost_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('analytics_landed_cost', 'igst_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('analytics_landed_cost', 'aidc_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('analytics_landed_cost', 'bcd_inr_paise_per_kg',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('analytics_landed_cost', 'partial_landed_cost_inr_paise_per_kg')
    op.drop_column('analytics_landed_cost', 'excluded_components')
    op.drop_column('analytics_landed_cost', 'is_complete')
    op.drop_column('analytics_landed_cost', 'sws_inr_paise_per_kg')
    op.create_table('ref_duty_rates',
    sa.Column('hs8', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bcd_pct', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=False),
    sa.Column('aidc_pct', sa.NUMERIC(precision=6, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('surcharge_pct', sa.NUMERIC(precision=6, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('igst_pct', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=False),
    sa.Column('source_note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('hs8', 'effective_from', name=op.f('ref_duty_rates_pkey'))
    )
    # (checkpoint_* table re-creation stripped by hand, same as before)
    op.drop_table('ref_duty_component_conflicts')
    op.drop_table('ref_duty_components')
    # ### end Alembic commands ###
    postgresql.ENUM(name='duty_verification_status').drop(op.get_bind(), checkfirst=True)
