"""initial trade pipeline warehouse schema

Revision ID: 2b3646342c9b
Revises: 
Create Date: 2026-08-23 00:38:59.702903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b3646342c9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Defined once, created explicitly before any table references it —
    # the raw autogenerated form re-declared this ENUM inline per column
    # (3x) with `create_type` left at its default True, which would issue
    # `CREATE TYPE cell_status` three times and fail on the 2nd. Postgres
    # has no native `CREATE TYPE IF NOT EXISTS`, so this uses the standard
    # DO-block idiom rather than SQLAlchemy's `checkfirst` (unreliable here
    # against the async driver in local testing — `checkfirst=True` still
    # attempted a duplicate CREATE).
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE cell_status AS ENUM (
                'OK', 'ZERO', 'NOT_REPORTED', 'SUPPRESSED', 'NOT_YET_PUBLISHED',
                'PROVISIONAL', 'QTY_MISSING', 'UNIT_MISMATCH', 'CODE_RETIRED', 'FETCH_FAILED'
            );
        EXCEPTION WHEN duplicate_object THEN null;
        END $$;
        """
    )
    cell_status_enum = postgresql.ENUM(
        'OK', 'ZERO', 'NOT_REPORTED', 'SUPPRESSED', 'NOT_YET_PUBLISHED', 'PROVISIONAL',
        'QTY_MISSING', 'UNIT_MISMATCH', 'CODE_RETIRED', 'FETCH_FAILED',
        name='cell_status',
        create_type=False,
    )

    op.create_table('analytics_coverage_summary',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('expected_cells', sa.Integer(), nullable=False),
    sa.Column('present_cells', sa.Integer(), nullable=False),
    sa.Column('not_yet_published_cells', sa.Integer(), nullable=False),
    sa.Column('suppressed_cells', sa.Integer(), nullable=False),
    sa.Column('fetch_failed_cells', sa.Integer(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hs6', 'flow', 'window_start', 'window_end')
    )
    op.create_table('analytics_landed_cost',
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('cif_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('bcd_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('aidc_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('surcharge_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('igst_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('landed_cost_inr_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('duty_rate_effective_from', sa.Date(), nullable=False),
    sa.Column('domestic_price_inr_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('margin_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('domestic_price_confidence', sa.Text(), nullable=False),
    sa.CheckConstraint("domestic_price_confidence IN ('good','limited','unavailable')", name='ck_alc_domestic_price_confidence'),
    sa.PrimaryKeyConstraint('hs8', 'month')
    )
    op.create_table('analytics_mismatch_checks',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.Text(), nullable=False),
    sa.Column('partner_country_code', sa.Text(), server_default=sa.text("'ALL_PARTNERS'"), nullable=False),
    sa.Column('gap_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('direction_flip_yoy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("check_name IN ('A_dgcis_vs_comtrade_india','B_dgcis_vs_partner_comtrade','C_dgcis_vs_baci')", name='ck_amc_check_name'),
    sa.CheckConstraint("severity IN ('quiet','flag','warning','untrustworthy')", name='ck_amc_severity'),
    sa.PrimaryKeyConstraint('hs6', 'flow', 'year', 'check_name', 'partner_country_code')
    )
    op.create_table('analytics_monthly_current_year',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('value_inr_paise', sa.BigInteger(), nullable=True),
    sa.Column('status', cell_status_enum, nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('mom_change_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('yoy_same_month_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hs6', 'flow', 'month')
    )
    op.create_table('analytics_partner_rankings',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('partner_country_code', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('value_inr_paise', sa.BigInteger(), nullable=True),
    sa.Column('status', cell_status_enum, nullable=False),
    sa.PrimaryKeyConstraint('hs6', 'flow', 'year', 'partner_country_code')
    )
    op.create_index('ix_apr_rank_where_present', 'analytics_partner_rankings', ['hs6', 'flow', 'year', 'rank'], unique=True, postgresql_where=sa.text('rank IS NOT NULL'))
    op.create_table('analytics_unit_value_series',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit_value_inr_paise_per_kg', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('delta_value_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('delta_from_qty_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('delta_from_price_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('delta_from_fx_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('coverage_gate_passed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hs6', 'flow', 'year')
    )
    op.create_table('dead_letter_ingestion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('job_run_id', sa.UUID(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_desc', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dead_letter_source_resolved', 'dead_letter_ingestion', ['source', 'resolved'], unique=False)
    op.create_table('normalized_trade_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('hs8', sa.Text(), nullable=True),
    sa.Column('hs_revision', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('calendar', sa.Text(), nullable=False),
    sa.Column('partner_country_code', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('universe', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('status', cell_status_enum, nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('value_inr_paise', sa.BigInteger(), nullable=True),
    sa.Column('value_original_currency_paise', sa.BigInteger(), nullable=True),
    sa.Column('fx_rate_used', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("basis IN ('CIF','FOB')", name='ck_ntf_basis'),
    sa.CheckConstraint("calendar IN ('CY','FY')", name='ck_ntf_calendar'),
    sa.CheckConstraint("currency IN ('INR','USD')", name='ck_ntf_currency'),
    sa.CheckConstraint("flow IN ('import','export')", name='ck_ntf_flow'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'hs6', 'hs8', 'flow', 'period_month', 'partner_country_code', 'dataset_version', name='uq_normalized_trade_flows')
    )
    op.create_index('ix_ntf_hs6_flow_period', 'normalized_trade_flows', ['hs6', 'flow', 'period_month'], unique=False)
    op.create_index('ix_ntf_hs8_flow_period', 'normalized_trade_flows', ['hs8', 'flow', 'period_month'], unique=False)
    op.create_table('raw_agmarknet_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('commodity', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('modal_price_inr_paise_per_qtl', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_date', 'commodity', 'market', name='uq_raw_agmarknet_prices')
    )
    op.create_table('raw_baci_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vintage', sa.Text(), nullable=False),
    sa.Column('hs_revision', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('exporter_code', sa.Text(), nullable=False),
    sa.Column('importer_code', sa.Text(), nullable=False),
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('value_fob_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vintage', 'year', 'exporter_code', 'importer_code', 'hs6', name='uq_raw_baci_records')
    )
    op.create_table('raw_comtrade_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('reporter_code', sa.Text(), nullable=False),
    sa.Column('partner_code', sa.Text(), nullable=False),
    sa.Column('flow_code', sa.Text(), nullable=False),
    sa.Column('cmd_code', sa.Text(), nullable=False),
    sa.Column('primary_value_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'reporter_code', 'partner_code', 'flow_code', 'cmd_code', name='uq_raw_comtrade_records')
    )
    op.create_table('raw_dgcis_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year', sa.Text(), nullable=False),
    sa.Column('calendar_month', sa.Date(), nullable=False),
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('partner_country', sa.Text(), nullable=False),
    sa.Column('value_inr_paise', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("flow IN ('import','export')", name='ck_raw_dgcis_monthly_flow'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year', 'calendar_month', 'hs8', 'flow', 'partner_country', name='uq_raw_dgcis_monthly')
    )
    op.create_table('ref_country_crosswalk',
    sa.Column('dgcis_country_name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dgcis_country_name')
    )
    op.create_table('ref_duty_rates',
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('bcd_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('aidc_pct', sa.Numeric(precision=6, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('surcharge_pct', sa.Numeric(precision=6, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('igst_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hs8', 'effective_from')
    )
    op.create_table('ref_hs6_hs8_crosswalk',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('hs6', 'hs8')
    )
    op.create_table('ref_hs_revision_notes',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hs6')
    )
    op.create_table('ref_regulatory_notes',
    sa.Column('hs6', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('hs6')
    )
    # NOTE: autogenerate also detected `checkpoints`/`checkpoint_writes`/
    # `checkpoint_blobs`/`checkpoint_migrations` as "removed" tables and
    # emitted drops for them here — those are LangGraph's own tables
    # (owned/created by `PostgresSaver.setup()`, app/graph.py), not ours.
    # They are deliberately absent from app.warehouse.schema.metadata and
    # must never be touched by this migration chain. Stripped by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (LangGraph's checkpoint-table re-creation stripped by hand — see the
    # matching note in upgrade(); this migration never touches them.)
    op.drop_table('ref_regulatory_notes')
    op.drop_table('ref_hs_revision_notes')
    op.drop_table('ref_hs6_hs8_crosswalk')
    op.drop_table('ref_duty_rates')
    op.drop_table('ref_country_crosswalk')
    op.drop_table('raw_dgcis_monthly')
    op.drop_table('raw_comtrade_records')
    op.drop_table('raw_baci_records')
    op.drop_table('raw_agmarknet_prices')
    op.drop_index('ix_ntf_hs8_flow_period', table_name='normalized_trade_flows')
    op.drop_index('ix_ntf_hs6_flow_period', table_name='normalized_trade_flows')
    op.drop_table('normalized_trade_flows')
    op.drop_index('ix_dead_letter_source_resolved', table_name='dead_letter_ingestion')
    op.drop_table('dead_letter_ingestion')
    op.drop_table('analytics_unit_value_series')
    op.drop_index('ix_apr_rank_where_present', table_name='analytics_partner_rankings', postgresql_where=sa.text('rank IS NOT NULL'))
    op.drop_table('analytics_partner_rankings')
    op.drop_table('analytics_monthly_current_year')
    op.drop_table('analytics_mismatch_checks')
    op.drop_table('analytics_landed_cost')
    op.drop_table('analytics_coverage_summary')
    # ### end Alembic commands ###
    postgresql.ENUM(name='cell_status').drop(op.get_bind(), checkfirst=True)
