"""add raw_dgcis_annual table

Revision ID: 85c781cf7550
Revises: bd25ffaf2537
Create Date: 2026-08-23 11:41:48.887825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85c781cf7550'
down_revision: Union[str, Sequence[str], None] = 'bd25ffaf2537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_dgcis_annual',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year_label', sa.Text(), nullable=False),
    sa.Column('hs8', sa.Text(), nullable=False),
    sa.Column('flow', sa.Text(), nullable=False),
    sa.Column('partner_country', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('value_inr_paise', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("flow IN ('import','export')", name='ck_raw_dgcis_annual_flow'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_label', 'hs8', 'flow', 'partner_country', name='uq_raw_dgcis_annual')
    )
    # (autogenerate also detected the checkpoint_* tables as "removed" —
    # LangGraph's own tables, not ours; see the earlier migrations' matching
    # notes. Stripped by hand.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (checkpoint_* table re-creation stripped by hand, same as before)
    op.drop_table('raw_dgcis_annual')
    # ### end Alembic commands ###
