"""expired duty rows keep their value_pct

Hand-written, not autogenerated: Alembic's autogenerate does not diff
CHECK constraint SQL bodies (only presence/absence by name), so the actual
rule change here (EXPIRED now keeps value_pct, matching
app.pipeline.duty_source.DutyComponentEvidence's corrected validator —
found via a real test: "preserve it for historical analysis" requires the
real historical number, not just the fact one once existed) had to be
written by hand. The autogenerated draft also only contained checkpoint-
table noise (LangGraph's own tables, not ours — see the two prior
migrations' matching notes), confirming there was nothing else to capture.

Revision ID: bd25ffaf2537
Revises: 14691feaef80
Create Date: 2026-08-23 01:41:21.173756

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd25ffaf2537'
down_revision: Union[str, Sequence[str], None] = '14691feaef80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('ck_rdc_value_matches_status', 'ref_duty_components', type_='check')
    op.create_check_constraint(
        'ck_rdc_value_matches_status',
        'ref_duty_components',
        "(verification_status IN ('VERIFIED','EXPIRED') AND value_pct IS NOT NULL) OR "
        "(verification_status IN ('NOT_VERIFIED','CONFLICTING') AND value_pct IS NULL)",
    )


def downgrade() -> None:
    op.drop_constraint('ck_rdc_value_matches_status', 'ref_duty_components', type_='check')
    op.create_check_constraint(
        'ck_rdc_value_matches_status',
        'ref_duty_components',
        "(verification_status = 'VERIFIED' AND value_pct IS NOT NULL) OR "
        "(verification_status != 'VERIFIED' AND value_pct IS NULL)",
    )
